# Financia Data Exploration 
In this we will explore Zerodhas and Growss Data Apis for Market Ingestion.

For more information follow this below links:[zerodha](https://zerodha.com/products/api/)
and [Groww](https://groww.in/trade-api/docs/python-sdk)

## 1. Exploring Groww API:

In [1]:
import pandas as pd
import numpy as np
from growwapi import GrowwAPI
import os
from dotenv import load_dotenv
import flask

load = load_dotenv()

In [2]:
# Accessing API
GrowApi = os.getenv('GrowwAPi')
GrowScret = os.getenv('GrowwScret')

groww = GrowwAPI(GrowApi)

instrument_df = groww.get_all_instruments()
instrument_df.head(10)

Ready to Groww!

,exchange,exchange_token,trading_symbol,groww_symbol,name,instrument_type,segment,series,isin,underlying_symbol,...,expiry_date,strike_price,lot_size,tick_size,freeze_quantity,is_reserved,buy_allowed,sell_allowed,internal_trading_symbol,is_intraday
0,NSE,66509,360ONE26NOV840CE,NSE-360ONE-23Nov26-840-CE,NaN,CE,FNO,NaN,NaN,360ONE,...,2026-11-23,840,500,0.05,20001,1,1,1,360ONE26NOV840CE,0
1,NSE,66520,360ONE26NOV1000PE,NSE-360ONE-23Nov26-1000-PE,NaN,PE,FNO,NaN,NaN,360ONE,...,2026-11-23,1000,500,0.05,20001,1,1,1,360ONE26NOV1000PE,0
2,NSE,39794,360ONE26OCT1560CE,NSE-360ONE-27Oct26-1560-CE,NaN,CE,FNO,NaN,NaN,360ONE,...,2026-10-27,1560,500,0.05,20001,1,1,1,360ONE26OCT1560CE,0
3,NSE,77681,360ONE26SEP1240PE,NSE-360ONE-29Sep26-1240-PE,NaN,PE,FNO,NaN,NaN,360ONE,...,2026-09-29,1240,500,0.05,20001,0,1,1,360ONE26SEP1240PE,0
4,NSE,68413,360ONE26SEPFUT,NSE-360ONE-29Sep26-FUT,NaN,FUT,FNO,NaN,NaN,360ONE,...,2026-09-29,-0.01,500,0.1,20001,0,1,1,360ONE26SEPFUT,0
5,NSE,66390,360ONE26OCT1100CE,NSE-360ONE-27Oct26-1100-CE,NaN,CE,FNO,NaN,NaN,360ONE,...,2026-10-27,1100,500,0.05,20001,0,1,1,360ONE26OCT1100CE,0
6,NSE,52659,360ONE26SEP1300PE,NSE-360ONE-29Sep26-1300-PE,NaN,PE,FNO,NaN,NaN,360ONE,...,2026-09-29,1300,500,0.05,20001,0,1,1,360ONE26SEP1300PE,0
7,NSE,52707,360ONE26OCT1280PE,NSE-360ONE-27Oct26-1280-PE,NaN,PE,FNO,NaN,NaN,360ONE,...,2026-10-27,1280,500,0.05,20001,0,1,1,360ONE26OCT1280PE,0
8,NSE,52651,360ONE26SEP1180PE,NSE-360ONE-29Sep26-1180-PE,NaN,PE,FNO,NaN,NaN,360ONE,...,2026-09-29,1180,500,0.05,20001,0,1,1,360ONE26SEP1180PE,0
9,NSE,77656,360ONE26SEP800PE,NSE-360ONE-29Sep26-800-PE,NaN,PE,FNO,NaN,NaN,360ONE,...,2026-09-29,800,500,0.05,20001,1,1,1,360ONE26SEP800PE,0

In [3]:
instrument_df.size

2823681

In [4]:
instrument_df['instrument_type'].unique()

array(['CE', 'PE', 'FUT', 'EQ', 'IDX'], dtype=object)

In [5]:
Equity_df = instrument_df[instrument_df['instrument_type'] == 'EQ']
Call_Opts = instrument_df[instrument_df['instrument_type'] == 'CE']
Put_Opts = instrument_df[instrument_df['instrument_type'] == 'PE']
FUT_Opts = instrument_df[instrument_df['instrument_type'] == 'FUT']
IDX_df = instrument_df[instrument_df['instrument_type'] == 'IDX']

Now lets split the Equity DF into Seperate data source and get list called the index. (You the ones that we trade).In order to get that data, we will  all type of companies in the index. (Simple google search will do).

In [6]:
# 1. Nifty Bank (BankNifty)
bank_nifty = [
    "HDFCBANK", "ICICIBANK", "SBIN", "AXISBANK", "KOTAKBANK", 
    "INDUSINDBK", "BANKBARODA", "PNB", "AUBANK", "FEDERALBNK", 
    "IDFCFIRSTB", "SBICARD"
]

# 2. Nifty IT
nifty_it = [
    "TCS", "INFY", "HCLTECH", "WIPRO", "TECHM", 
    "LTIM", "PERSISTENT", "COFORGE", "MPHASIS", "KPITTECH"
]

# 3. Nifty Pharma
nifty_pharma = [
    "SUNPHARMA", "DRREDDY", "CIPLA", "LUPIN", "DIVISLAB", 
    "AUROPHARMA", "BIOCON", "ALKEM", "IPCALAB", "GLENMARK"
]

# 4. Nifty Financial Services (FinNifty)
nifty_financial_services = [
    "HDFCBANK", "ICICIBANK", "AXISBANK", "KOTAKBANK", "SBIN", 
    "BAJFINANCE", "BAJAJFINSV", "SBILIFE", "HDFCLIFE", "CHOLAFIN"
]

# 5. Nifty FMCG
nifty_fmcg = [
    "ITC", "HINDUNILVR", "NESTLEIND", "BRITANNIA", "DABUR", 
    "MARICO", "GODREJCP", "COLPAL", "VBL", "TATACONSUM"
]

# 6. Nifty Auto
nifty_auto = [
    "MARUTI", "M&M", "TATAMOTORS", "BAJAJ-AUTO", "TVSMOTOR", 
    "HEROMOTOCO", "EICHERMOT", "ASHOKLEY", "BHARATFORG", "MOTHERSON"
]

# 7. Nifty Infrastructure (Nifty Infra)
nifty_infra = [
    "RELIANCE", "TATASTEEL", "LT", "NTPC", "POWERGRID", 
    "BHARTIARTL", "ADANIPORTS", "ONGC", "GAIL", "ULTRACEMCO"
]

# 8. Nifty Oil and Gas
nifty_oil_and_gas = [
    "RELIANCE", "ONGC", "IOC", "BPCL", "HPCL", 
    "GAIL", "PETRONET", "OIL", "GUJGASLTD", "ATGL"
]

# 9. Nifty Media
nifty_media = [
    "SUNTV", "ZEEL", "PVRINOX", "NETWORK18", "TV18BRDCST", 
    "SAREGAMA", "NAZARA", "TIPSMUSIC", "DBCORP", "ZEEMEDIA"
]

# 10. Nifty Metal
nifty_metal = [
    "TATASTEEL", "HINDALCO", "JSWSTEEL", "VEDL", "JINDALSTEL", 
    "COALINDIA", "NMDC", "SAIL", "APLAPOLLO", "HINDZINC"
]

# 11. Nifty Private Bank
nifty_private_bank = [
    "HDFCBANK", "ICICIBANK", "AXISBANK", "KOTAKBANK", 
    "INDUSINDBK", "AUBANK", "FEDERALBNK", "IDFCFIRSTB", "RBLBANK", "CUB"
]

# 12. Nifty PSU Bank
nifty_psu_bank = [
    "SBIN", "BANKBARODA", "PNB", "CANBK", "UNIONBANK", 
    "IOB", "BANKINDIA", "MAHABANK", "CENTRALBK", "UCOBANK"
]

# 13. Nifty Realty
nifty_realty = [
    "DLF", "GODREJPROP", "OBEROIRLTY", "PHOENIXLTD", "BRIGADE", 
    "PRESTIGE", "LODHA", "Sobha", "MAHLIFE", "SUNTECK"
]

# 14. Nifty Commodities
nifty_commodities = [
    "RELIANCE", "TATASTEEL", "HINDALCO", "JSWSTEEL", "ONGC", 
    "COALINDIA", "ULTRACEMCO", "GRASIM", "UPL", "IOC"
]

# 15. Nifty Healthcare Index
nifty_healthcare = [
    "SUNPHARMA", "DRREDDY", "CIPLA", "DIVISLAB", "MAXHEALTH", 
    "APOLLOHOSP", "LUPIN", "AUROPHARMA", "ALKEM", "MEDANTA"
]

# 16. Nifty Consumer Durables
nifty_consumer_durables = [
    "TITAN", "HAVLLS", "VOLTAS", "WHIRLPOOL", "DIXON", 
    "AMBER", "BLUESTARCO", "CERA", "CROMPTON", "KAJARIACER"
]

For now lets create a simple duckdb warehouse to store results

In [ ]:
Equity_df.head(10)

,exchange,exchange_token,trading_symbol,groww_symbol,name,instrument_type,segment,series,isin,underlying_symbol,...,expiry_date,strike_price,lot_size,tick_size,freeze_quantity,is_reserved,buy_allowed,sell_allowed,internal_trading_symbol,is_intraday
84110,NSE,30232,1075SCL35,NSE-1075SCL35,Sammaan Capital Limited Mar'35,EQ,CASH,N1,INE148I07WR7,NaN,...,NaN,NaN,1,0.01,NaN,NaN,1,1,1075SCL35-N1,0
84111,NSE,763206,10MWL29,NSE-10MWL29,Mangalam Worldwide Limited Apr'29,EQ,CASH,N0,INE0JYY07026,NaN,...,NaN,NaN,1,0.01,NaN,NaN,1,1,10MWL29-N0,0
84112,NSE,2871,10IIFL28A,NSE-10IIFL28A,Iifl Finance Limited Jun'28,EQ,CASH,NE,INE530B08094,NaN,...,NaN,NaN,1,0.01,NaN,NaN,1,1,10IIFL28A-NE,0
84113,NSE,12465,10CAGL27,NSE-10CAGL27,Creditaccess Grameen Limited Nov'27,EQ,CASH,N5,INE741K07496,NaN,...,NaN,NaN,1,0.01,NaN,NaN,1,1,10CAGL27-N5,0
84114,NSE,14710,1015SCL28A,NSE-1015SCL28A,Sammaan Capital Limited Mar'28,EQ,CASH,AL,INE148I07OH5,NaN,...,NaN,NaN,1,0.01,NaN,NaN,1,1,1015SCL28A-AL,0
84115,NSE,23323,1025SCL34,NSE-1025SCL34,Sammaan Capital Limited Mar'34,EQ,CASH,Z8,INE148I07SQ7,NaN,...,NaN,NaN,1,0.01,NaN,NaN,1,1,1025SCL34-Z8,0
84116,NSE,23303,1015SCFL29,NSE-1015SCFL29,Sammaan Capital Limited Mar'29,EQ,CASH,YY,INE148I07SS3,NaN,...,NaN,NaN,1,0.01,NaN,NaN,1,1,1015SCFL29-YY,0
84117,NSE,20779,1003ISFL28,NSE-1003ISFL28,Iifl Samasta Finance Limited Dec'28,EQ,CASH,N4,INE413U07269,NaN,...,NaN,NaN,1,0.01,NaN,NaN,1,1,1003ISFL28-N4,0
84118,NSE,25914,1025UCL26A,NSE-1025UCL26A,Ugro Capital Limited Oct'26,EQ,CASH,N1,INE583D07521,NaN,...,NaN,NaN,1,0.01,NaN,NaN,1,1,1025UCL26A-N1,0
84119,NSE,28925,1015SCL29T,NSE-1015SCL29T,Sammaan Capital Limited Dec'29,EQ,CASH,N1,INE148I07VO6,NaN,...,NaN,NaN,1,0.01,NaN,NaN,1,1,1015SCL29T-N1,0